
services:
  postgres-budget-book:
    image: postgres:13.3
    environment:
      POSTGRES_USER: budget # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: secret # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: budget_db # The PostgreSQL default database (automatically created at first launch)
    restart: unless-stopped
    ports:
      - "5432:5432"