version: '3'

volumes:
  budget_book_postgres_data:
    driver: local

services:
  postgres-budget-book:
    image: postgres:13.3
    volumes:
      - budget_book_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"